const songs = [
  {
    title: "Nature loving sounds calm",
    length: 5,
    img: "http://localhost:5000/images/image-1.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "beginners",
    isRealLength: false,
  },
  {
    title: "Pjesma neka opustajuca",
    length: 10,
    img: "http://localhost:5000/images/image-2.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "stress relief",

    isRealLength: false,
  },
  {
    title: "Prelijepa pjesma za slusanje",
    length: 15,
    img: "http://localhost:5000/images/image-3.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "sleep",

    isRealLength: false,
  },
  {
    title: "Zlatno polje u daljini šumi",
    length: 20,
    img: "http://localhost:5000/images/image-4.jpg",
    song: "http://localhost:5000/songs/med20.mp3",
    category: "happiness",

    isRealLength: true,
  },
  {
    title: "Sunce izlazi iza brda",
    length: 5,
    img: "http://localhost:5000/images/image-5.jpg",
    song: "http://localhost:5000/songs/med5.mp3",
    category: "relaxation",

    isRealLength: true,
  },
  {
    title: "Rain falling on umbrela ",
    length: 10,
    img: "http://localhost:5000/images/image-6.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",

    category: "stress relief",
    isRealLength: false,
  },
  {
    title: "Snowie night ambient in caffe",
    length: 15,
    img: "http://localhost:5000/images/image-7.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "sleep",
    isRealLength: false,
  },
  {
    title: "A bit longer song to meditate",
    length: 20,
    img: "http://localhost:5000/images/image-8.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "sleep",
    isRealLength: false,
  },
  {
    title: "Rosno polje mirise u zoru",
    length: 10,
    img: "http://localhost:5000/images/image-9.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "stress relief",
    isRealLength: false,
  },
  {
    title: "Gleceri se tope na sjeveru",
    length: 5,
    img: "http://localhost:5000/images/image-10.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "sleep",
    isRealLength: false,
  },
  {
    title: "Nebo je plavo i opustena varijanta",
    length: 15,
    img: "http://localhost:5000/images/image-11.jpg",
    song: "http://localhost:5000/songs/med15.mp3",
    category: "stress relief",
    isRealLength: true,
  },
  {
    title: "Pjesma meditirajuce ljepote",
    length: 5,
    img: "http://localhost:5000/images/image-12.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "beginners",
    isRealLength: false,
  },
  {
    title: "Mjesecina sija iznad grada",
    length: 10,
    img: "http://localhost:5000/images/image-13.jpg",
    song: "http://localhost:5000/songs/med10.mp3",
    category: "beginners",
    isRealLength: true,
  },
  {
    title: "Nasmijani suncokret",
    length: 15,
    img: "http://localhost:5000/images/image-14.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "happiness",
    isRealLength: false,
  },
  {
    title: "Oblacno vrijeme s kisom",
    length: 5,
    img: "http://localhost:5000/images/image-15.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "sleep",
    isRealLength: false,
  },
  {
    title: "Odlicna pjesma za opustanje poslije posla",
    length: 10,
    img: "http://localhost:5000/images/image-16.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "happiness",
    isRealLength: false,
  },
  {
    title: "Prelijepa varijanta slonovog plesa u zoru",
    length: 15,
    img: "http://localhost:5000/images/image-17.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "relaxation",
    isRealLength: false,
  },
  {
    title: "Relaxing sound of anything playing",
    length: 20,
    img: "http://localhost:5000/images/image-18.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "walking",
    isRealLength: false,
  },
  {
    title: "I am running out of ideas",
    length: 5,
    img: "http://localhost:5000/images/image-19.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "relaxation",
    isRealLength: false,
  },
  {
    title: "It is nice to be calm",
    length: 10,
    img: "http://localhost:5000/images/image-20.jpg",
    song: "http://localhost:5000/songs/med10.mp3",
    category: "walking",
    isRealLength: true,
  },
  {
    title: "Generate new mindful meditaton song",
    length: 15,
    img: "http://localhost:5000/images/image-21.jpg",
    song: "http://localhost:5000/songs/default-short.mp3",
    category: "relaxation",
    isRealLength: false,
  },
  {
    title: "All is green around and nature",
    length: 20,
    img: "http://localhost:5000/images/image-22.jpg",
    song: "http://localhost:5000/songs/med20.mp3",
    category: "walking",
    isRealLength: true,
  },
];

module.exports = songs;
